[local]
localhost ansible_connection=local

[development]
# Exemple avec des serveurs distants
# 192.168.1.10 ansible_user=ubuntu
# 192.168.1.11 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3